### ISSUE TITLE
What is the difference between the KaldiOpType and KaldiOps?

### ISSUE THREAD

**Issue by yzmyyff** [XiaoMi/kaldi-onnx#12]

**Comment by TonyMou** [comment]
One is a enum, the other is a list.

**Comment by yzmyyff** [comment]
I know they have different types. Why we create a list and an enum to represent the same thing.

**Comment by TonyMou** [comment]
To make the code safe and clean. KaldiOpType is an interface to fetch a type from KaldiOps list.
