### ISSUE TITLE
 What is the difference between 'consts' and 'attributes'?

### ISSUE THREAD

**Issue by JiayiFu** [XiaoMi/kaldi-onnx#15]
Why the 'offset' of 'KaldiOpType.Offset is an attribute but the 'offsets' of KaldiOpType.ScaleOffset is a const? 
How to judge whether a value in the 'mdl' file an 'attribute' or a 'const'?

**Comment by TonyMou** [comment]
A const is for trainable values and always is an array.
KaldiOpType.ScaleOffset represents Kaldi's ScaleAndOffsetComponent. The 'scales' and 'offstes' are both trainable.

An attribute is a parameter value or list. KaldiopType.Offset is for Offset Descriptor in Kaldi, e.g. Offset(input, -1), '-1' is an attribute value here.

**Comment by JiayiFu** [comment]
> A const is for trainable values and always is an array.
> KaldiOpType.ScaleOffset represents Kaldi's ScaleAndOffsetComponent. The 'scales' and 'offstes' are both trainable.
> 
> An attribute is a parameter value or list. KaldiopType.Offset is for Offset Descriptor in Kaldi, e.g. Offset(input, -1), '-1' is an attribute value here.

But I found 'time_offsets' in 'KaldiOpType.Tdnn.name' is a const. But 'time_offsets' in Tdnn is not trainable. Is this a mistake?

**Comment by TonyMou** [comment]
Is it possible that time_offsets would be a long vector? Sometimes, we also save large vectors as weights.
