### ISSUE TITLE
Sum Descriptor parser error

### ISSUE THREAD

**Issue by yzmyyff** [XiaoMi/kaldi-onnx#2]
We use ```,``` to split config in function ```parse_sum_descp```. It will fail if this descriptor refers to other descriptor, for example 
```
Sum(Scale(0.66, tdnnf7.dropout), tdnnf8.dropout)
```

**Comment by TonyMou** [comment]
Thanks for your testing. This using case of 'Sum' descriptor was not supported yet. We are looking into it and try to make it work.

**Comment by yzmyyff** [comment]
How about to depend on kaldi srcs directly. We can just convert its components and don't need to generate a computation graph from scratch.

**Comment by TonyMou** [comment]
We need a computation graph to make an ONNX model.

**Comment by TonyMou** [comment]
@yzmyyff Already fixed. Feel free to reopen this issue if there is any problem.
