### ISSUE TITLE
Can onnx model convert back to kaldi 

### ISSUE THREAD

**Issue by panxin801** [XiaoMi/kaldi-onnx#20]
Hello, I want to ask if a ONNX model maybe trained from CNTK, converts baack to kaldi is supported? Thank you for the time and help.

**Comment by TonyMou** [comment]
Not support yet.

**Comment by zhang7346** [comment]
@TonyMou  Is there any plan for this? looking forward to this.

**Comment by tonylt** [comment]
Sorry, we have no plan for this feature recently.
