### ISSUE TITLE
转出来的onnx模型无法使用, 报错ReplaceIndex未注册

### ISSUE THREAD

**Issue by tz301** [XiaoMi/kaldi-onnx#25]
使用onnxruntime工具载入onnx模型时, 报错Fatal error: ReplaceIndex is not a registered function/op. 如何解决？

**Comment by lu229** [comment]
@tz301 貌似发错地方了?

**Comment by tz301** [comment]
> @tz301 貌似发错地方了?

我用的kaldi-onnx工具，将kaldi的模型转成onnx的，但是没法使用，如果成功转成了可用的onnx模型，用onnxruntime工具就可以正常使用了。好像和kaldi-onnx工具内ReplaceIndex的实现有关，onnx并没有ReplaceIndex这个op。

**Comment by lu229** [comment]
@tz301 这个问题我咨询了一下@TonyMou, 这个是这样, ReplaceIndex这个算子是kaldi的, 标准的ONNX中并不支持, 转成ONNX模型之后, 这个ONNX模型可以到[MACE](https://github.com/XiaoMi/mace)里面转换并运行, 但是onnxruntime是不支持的.

**Comment by tz301** [comment]
@lu229 这个有没有可能支持呢，毕竟这个项目叫kaldi-onnx，而不是kaldi-mace，转出来的onnx模型onnx不能用很奇怪。ReplaceIndex在kaldi主流的tdnn或者cnn_tdnn模型里都是很常用的，例如用一些onnx支持的op来实现ReplaceIndex？

**Comment by lu229** [comment]
@tz301 这个需要我们去开发onnxruntime, 目前我们的事情比较多, 还没有精力去兼顾, 以后有时间了可能会去支持....
