### ISSUE TITLE
Can I delete this parameter？ --raw=true   is error when run nnet3-copy 

### ISSUE THREAD

**Issue by l2009312042** [XiaoMi/kaldi-onnx#29]
ERROR (nnet3-copy[5.5.543~2-7249c]:Read():parse-options.cc:365) Invalid option --raw=true

**Comment by SuperYuLu** [comment]
Got same error as stated above

**Comment by SuperYuLu** [comment]
Hey, I just figured it out. Simply ignore '--raw=true' doesn't hurt

**Comment by julianyulu** [comment]
Hey, I just figured it out. Simply ignore '--raw=true' doesn't hurt
