### ISSUE TITLE
Please support GeneralDropoutComponent

### ISSUE THREAD

**Issue by yzmyyff** [XiaoMi/kaldi-onnx#3]
This component is often used in tdnnf-layer

**Comment by TonyMou** [comment]
We'll look into it.

**Comment by TonyMou** [comment]
The dropout-type components are usually not used in inference. It would be removed if you use nnet3-copy your .mdl file with prepare-for-test=true.

**Comment by yzmyyff** [comment]
I used this option, it didn't work.

**Comment by TonyMou** [comment]
Fixed! Thanks for testing.
