### ISSUE TITLE
converter net3 model error！

### ISSUE THREAD

**Issue by qiufengyun** [XiaoMi/kaldi-onnx#6]
finished parsing nnet3 (110) components.
left_context: 1, right context: 1
model has 146 nodes.
start making ONNX model.
Traceback (most recent call last):
  File "converter/convert.py", line 202, in <module>
    main()
  File "converter/convert.py", line 188, in main
    onnx_model = converter.run()
  File "converter/convert.py", line 71, in run
    onnx_model = g.run()
  File "/data/aiwork/kaldi-onnx/converter/graph.py", line 113, in run
    onnx_model = self.make_model()
  File "/data/aiwork/kaldi-onnx/converter/graph.py", line 747, in make_model
    value_info=internal_inputs)
TypeError: make_graph() got an unexpected keyword argument 'value_info'

**Comment by TonyMou** [comment]
which version of onnx are you using?

**Comment by qiufengyun** [comment]
> 你使用的是哪个版本的onnx？升级你的onnx。

onnx 1.3.0

**Comment by TonyMou** [comment]
Could you provide more info? Cannot reproduce your problem.

**Comment by qiufengyun** [comment]
> Could you provide more info? Cannot reproduce your problem.

tdnn-f Trained chain model. Is that the reason? Whether to support chain mode?

**Comment by TonyMou** [comment]
It possibly is a problem related to your environment. Could u provide your .mdl for testing?

**Comment by qiufengyun** [comment]
> It possibly is a problem related to your environment. Could u provide your .mdl for testing?
Baidu Disk Address：https://pan.baidu.com/s/1WkBZUzZilqT8A2nrJiVjPg 
Extraction code：odre

**Comment by TonyMou** [comment]
I have successfully converted your model to ONNX model.
Before converting, need to run the following command.
```
/path/to/kaldi/src/nnet3bin/nnet3-am-copy --binary=false \
                                                                   --prepare-for-test \
                                                                   --raw=true \
                                                                   path/to/final.mdl \
                                                                   path/to/tdnnf-test.mdl
```

You can download the onnx model from:
https://cnbj1.fds.api.xiaomi.com/mace/kaldi-onnx/tdnnf-test.onnx?GalaxyAccessKeyId=5151729087601&Expires=1559651564328&Signature=k1X9k62J9PUGeSUvTlkabhG+Ai4=
