### ISSUE TITLE
Why do we pass the empty list "input" into class Graph

### ISSUE THREAD

**Issue by yzmyyff** [XiaoMi/kaldi-onnx#8]
What's the meaning of the "input" attribute in Graph?
Before initializing class Graph we saved all model input in  Converter._input_dims and did nothing about _input. Why we pass the empty list "input" into graph?

**Comment by TonyMou** [comment]
It is not used actually. We kept this as an interface.

**Comment by yzmyyff** [comment]
@TonyMou Got it, thanks a lot.

**Comment by TonyMou** [comment]
Suggestions and contributions are welcomed!
